[package]
name = "datafusion-memtable"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
arrow = "57.0.0"
datafusion = "51.0.0"
tokio = {version = "1.48.0", features=["rt-multi-thread"]}
